#!/usr/bin/env python3
import argparse
import boto3
import json
import os
import sys
from botocore.exceptions import ClientError


def load_file(path):
    with open(path, "r") as f:
        return f.read()


def write_file(path, content):
    with open(path, "w") as f:
        f.write(content)


def call_bedrock_qwen(model_arn, region, prompt):
    """
    Invoke AWS Bedrock Qwen model using the correct ChatCompletion format.
    """

    client = boto3.client("bedrock-runtime", region_name=region)

    # Example ARN:
    # arn:aws:bedrock:us-east-1::foundation-model/qwen.qwen3-coder-30b-a3b-v1:0
    model_id = model_arn.split("/")[-1]

    body = {
        "messages": [
            {
                "role": "user",
                "content": prompt
            }
        ],
        "max_completion_tokens": 2048,
        "temperature": 0.3,
    }

    try:
        response = client.invoke_model(
            modelId=model_id,
            body=json.dumps(body),
            contentType="application/json",
            accept="application/json"
        )

        response_json = json.loads(response["body"].read())

        # Qwen returns output_text
        return response_json.get("output_text", "")

    except ClientError as e:
        print("ERROR calling Bedrock:", e, file=sys.stderr)
        sys.exit(1)


def build_prompt(trivy_json):
    return f"""
You are a senior DevSecOps engineer.

Your task:
- Read the Trivy scan report shown below.
- Based on the vulnerabilities in the report,
  generate a *unified diff patch* (git .diff format) that a developer can apply to fix the issues.
- Patch may update Dockerfile, dependencies, or config files.
- If no fixes are realistic, return an empty string.
- DO NOT include explanations, only the raw diff.

Trivy Report:
{trivy_json}

Output rules:
- Output ONLY the diff.
- No markdown.
- No commentary.
"""


def main():
    parser = argparse.ArgumentParser(description="Send Trivy report to AWS Bedrock (Qwen) for patch suggestions")
    parser.add_argument("--report", required=True, help="Path to Trivy report JSON")
    parser.add_argument("--model-arn", required=True, help="AWS Bedrock foundation model ARN")
    parser.add_argument("--mock", required=True, choices=["true", "false"], help="Mock mode")
    parser.add_argument("--out", required=True, help="Output diff file")

    args = parser.parse_args()

    # Load Trivy JSON report
    trivy_json = load_file(args.report)

    # Mock mode – useful for workflow testing
    if args.mock == "true":
        print("[MOCK MODE] Returning placeholder diff")
        fake_diff = """\
diff --git a/Dockerfile b/Dockerfile
index 111111..222222 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,4 @@
-FROM ubuntu:18.04
+FROM ubuntu:22.04
 RUN apt-get update && apt-get install -y python3
 CMD ["python3", "app.py"]
"""
        write_file(args.out, fake_diff)
        return

    # Build the model prompt
    prompt = build_prompt(trivy_json)

    output_text = call_bedrock_qwen(
        model_arn=args.model_arn,
        region=os.environ.get("AWS_REGION", "us-east-1"),
        prompt=prompt,
    )

    diff = output_text.strip()

    if diff == "":
        print("No patch generated by Qwen. Writing empty file.")
    else:
        print("Patch generated by Qwen.")

    write_file(args.out, diff)


if __name__ == "__main__":
    main()
